name: Deploy React CSR
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Build
        run: npm run build
      - name: upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: |
            dist
            public

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
      - name: List all files
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."
