name: Deploy React CSR
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened

# env:
#   BUN_VERSION: 1.2.18

jobs:
  build:
    # environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Print Bun version
        run: echo "Bun version:${{ vars.BUN_VERSION }}"
      - name: Print API Key
        run: echo "API Key:${{ secrets.API_KEY }}"

      - name: Get Code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: |
            dist
            public
      - name: Force failed
        run: exit 1

  deploy:
    # if: github.ref == 'refs/heads/main'
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
      - name: List all files
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."
  notify-success:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    # if: always()
    if: success()
    steps:
      # - name: Notify to Discord Text Channel 1
      #   env:
      #     DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY"
      #   uses: Ilshidur/action-discord@master
      #   with:
      #     # args: "${{ github.sha }} by Knightington EECU 104"
      #     args: "Deploy Success! by Knightington EECU 104"

      - name: Notify to Discord - Awesome Galaxy
        env:
          DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1421698037386055700/neXYAmukhFUZ5dAsKP477E9shixsMec5GtPZvWHwp-JKEZy4KKz7M6nQ4G2n608XgbxR"
        uses: Ilshidur/action-discord@master
        with:
          args: "Deploy Success! by Knightington EECU 104"

  notify-failure:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    if: failure()
    steps:
      # - name: Notify to Discord Text Channel 1
      #   env:
      #     DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY"
      #   uses: Ilshidur/action-discord@master
      #   with:
      #     # args: "${{ github.sha }} by Knightington EECU 104"
      #     args: "Deploy Failed! by Knightington EECU 104"

      - name: Notify to Discord - Awesome Galaxy
        env:
          DISCORD_WEBHOOK: "https://discord.com/api/webhooks/1421698037386055700/neXYAmukhFUZ5dAsKP477E9shixsMec5GtPZvWHwp-JKEZy4KKz7M6nQ4G2n608XgbxR"
        uses: Ilshidur/action-discord@master
        with:
          args: "Deploy Failed! by Knightington EECU 104"
