name: Deploy React CSR
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened

# env:
#   BUN_VERSION: 1.2.18

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Bun version
        run: echo "Bun version:${{ vars.BUN_VERSION }}"
      - name: Print API Key
        run: echo "API Key:${{ secrets.API_KEY }}"

      - name: Get Code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: |
            dist
            public

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
      - name: List all files
        run: ls -R
      - name: Deploy
        run: echo "Deploying..."
