name: Lint
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Install and cache dependencies
        uses: ./.github/actions/install-and-caching
      - name: Install deps
        run: npm install
      - name: Lint
        run: npm run lint
